---
abstract: 'String::Util -- String processing utilities'
author:
    - "Miko O'Sullivan <miko@idocs.com>"
    - "Scott Baker <scott@perturb.org>"
generated_by: home grown
license: perl
name: String-Util
provides:
    String::Util:
        file: lib/String/Util.pm
        version: 1.30
requires:
    Test::More: 0
    perl: 5.003
version: 1.30
